#!/usr/bin/env node
// Server-side activation for the self-hosted PM2 deployment.
// Usage: node deploy/self-hosted/activate.mjs <absolute-release-path>
// Runs migrations, rewrites the PM2 ecosystem to point at the new release,
// reloads web/worker, refreshes the display nginx mount, and waits for health.
// Never prints secret values.

import { spawnSync } from 'node:child_process';
import { chmodSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const NODE24 = '/opt/node-v24.21.0-linux-x64/bin';
const PRIVATE_DIR = '/opt/codex-status-dashboard/private';
const ECOSYSTEM_DIR = '/etc/codex-status-dashboard';
const ECOSYSTEM_PATH = `${ECOSYSTEM_DIR}/ecosystem.config.cjs`;
const EDGE_ENV_PATH = `${PRIVATE_DIR}/compose-edge.env`;
const RUNTIME_AUTH = '/opt/codex-status-dashboard/runtime-auth';

const release = resolve(process.argv[2] ?? '');
if (!release.startsWith('/opt/codex-status-dashboard/pm2-releases/') || release.endsWith('.extracting')) {
  console.error('activate: release path must be under /opt/codex-status-dashboard/pm2-releases/');
  process.exit(2);
}

function loadEnvFile(path) {
  const env = {};
  for (const line of readFileSync(path, 'utf8').split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq < 1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    env[key] = value;
  }
  return env;
}

function run(command, args, options = {}) {
  const result = spawnSync(command, args, { stdio: 'inherit', ...options });
  if (result.error || result.status !== 0) {
    console.error(`activate: command failed: ${command} ${args.join(' ')}`);
    process.exit(1);
  }
}

const secrets = loadEnvFile(`${PRIVATE_DIR}/.env`);
for (const key of ['DB_PASSWORD', 'APP_ORIGIN', 'DEVICE_REGISTRATION_SECRET', 'PROVIDER_CREDENTIAL_KEY']) {
  if (!secrets[key]) {
    console.error(`activate: private/.env is missing ${key}`);
    process.exit(1);
  }
}

const databaseUrl = `postgresql://dashboard:${encodeURIComponent(secrets.DB_PASSWORD)}@127.0.0.1:5432/codex_status_dashboard`;
const workerProxy = secrets.WORKER_PROXY ?? '';
const workerNoProxy = secrets.WORKER_NO_PROXY ?? 'localhost,127.0.0.1';

// 1. Edge services (db with host port mapping, display nginx) must be up before migrating.
writeFileSync(EDGE_ENV_PATH, `DISPLAY_RELEASE=${release}\n`, { mode: 0o600 });
run('docker', [
  'compose',
  '--env-file', `${PRIVATE_DIR}/.env`,
  '--env-file', EDGE_ENV_PATH,
  '-f', `${release}/deploy/compose.self-hosted-edge.yaml`,
  'up', '-d',
]);

// 2. Database migration (one-shot, replaces the old migrate container).
run(`${release}/node_modules/.bin/tsx`, [`${release}/scripts/migrate.ts`], {
  env: {
    ...process.env,
    PATH: `${NODE24}:${process.env.PATH}`,
    DATABASE_DIRECT_URL: databaseUrl,
  },
});

// 3. Rewrite the PM2 ecosystem to point at the new release.
mkdirSync(ECOSYSTEM_DIR, { recursive: true, mode: 0o700 });
const webEnv = {
  NODE_ENV: 'production',
  NEXT_TELEMETRY_DISABLED: '1',
  DATABASE_URL: databaseUrl,
  DATABASE_DIRECT_URL: databaseUrl,
  APP_ORIGIN: secrets.APP_ORIGIN,
  DASHBOARD_DISPLAY_ORIGINS: secrets.DASHBOARD_DISPLAY_ORIGINS ?? '',
  DASHBOARD_USER_TOKEN_FILE: `${PRIVATE_DIR}/user-token`,
  DEVICE_REGISTRATION_SECRET: secrets.DEVICE_REGISTRATION_SECRET,
  PROVIDER_CREDENTIAL_KEY: secrets.PROVIDER_CREDENTIAL_KEY,
};
const workerEnv = {
  NODE_ENV: 'production',
  PATH: `${NODE24}:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`,
  DATABASE_DIRECT_URL: databaseUrl,
  PROVIDER_CREDENTIAL_KEY: secrets.PROVIDER_CREDENTIAL_KEY,
  PROVIDER_ACCOUNTS_FILE: `${PRIVATE_DIR}/provider-accounts.json`,
  PROVIDER_SECRETS_ROOT: `${PRIVATE_DIR}/secrets`,
  CODEX_RUNTIME_ROOT: `${RUNTIME_AUTH}/codex`,
  KIMI_RUNTIME_HOME: `${RUNTIME_AUTH}/kimi`,
  KIMI_CLI_COMMAND: '/usr/local/bin/kimi-runtime',
  NODE_USE_ENV_PROXY: '1',
  HTTP_PROXY: workerProxy,
  HTTPS_PROXY: workerProxy,
  ALL_PROXY: workerProxy,
  NO_PROXY: workerNoProxy,
};
const ecosystem = `// Generated by deploy/self-hosted/activate.mjs — do not edit by hand.
module.exports = {
  apps: [
    {
      name: 'dashboard-web',
      cwd: ${JSON.stringify(release)},
      script: 'node_modules/.bin/next',
      args: 'start --hostname 127.0.0.1 --port 3100',
      interpreter: ${JSON.stringify(`${NODE24}/node`)},
      env: ${JSON.stringify(webEnv, null, 2)},
    },
    {
      name: 'dashboard-worker',
      cwd: ${JSON.stringify(release)},
      script: 'node_modules/.bin/tsx',
      args: 'src/worker/provider-runtime.ts',
      interpreter: ${JSON.stringify(`${NODE24}/node`)},
      env: ${JSON.stringify(workerEnv, null, 2)},
    },
  ],
};
`;
writeFileSync(ECOSYSTEM_PATH, ecosystem, { mode: 0o600 });
chmodSync(ECOSYSTEM_PATH, 0o600);

// 4. Reload processes and persist for resurrection.
run('pm2', ['startOrReload', ECOSYSTEM_PATH, '--only', 'dashboard-web,dashboard-worker']);
run('pm2', ['save']);

// 5. Wait for web health; leave processes running and fail the deploy on timeout.
let healthy = false;
for (let attempt = 0; attempt < 30; attempt++) {
  const probe = spawnSync('curl', ['-fsS', '-m', '5', 'http://127.0.0.1:3100/api/health'], { stdio: 'pipe' });
  if (probe.status === 0) { healthy = true; break; }
  spawnSync('sleep', ['2']);
}
if (!healthy) {
  console.error('activate: web did not become healthy on 127.0.0.1:3100');
  process.exit(1);
}
const displayProbe = spawnSync('curl', ['-fsS', '-m', '5', '-o', '/dev/null', 'http://127.0.0.1:3101/display/'], { stdio: 'pipe' });
if (displayProbe.status !== 0) {
  console.error('activate: display did not answer on 127.0.0.1:3101');
  process.exit(1);
}
const workerStatus = spawnSync('pm2', ['jlist'], { encoding: 'utf8' });
const processes = workerStatus.status === 0 ? JSON.parse(workerStatus.stdout) : [];
const worker = processes.find(p => p.name === 'dashboard-worker');
if (!worker || worker.pm2_env?.status !== 'online') {
  console.error('activate: dashboard-worker is not online');
  process.exit(1);
}
console.log(`activate: ${release} is live (web healthy, display ok, worker online).`);
